FROM eclipse-temurin:17-jre
RUN mkdir -p /app/data
WORKDIR /app
COPY target/droptop-0.0.1-SNAPSHOT.jar /app/app.jar
EXPOSE 8080
CMD ["sh", "-c", "java -jar \
  -DBASELINKER_TOKEN=$BASELINKER_TOKEN \
  -DDATABASE-IP=$DATABASE_IP \
  -DDATABASE-NAME=$DATABASE_NAME \
  -DDATABASE-PASSWORD=$DATABASE_PASSWORD \
  -DDATABASE-USERNAME=$DATABASE_USERNAME \
  -DPLATON_API_PROD=$PLATON_API_PROD \
  -DPLATON_CHECKORDERSTATUS=$PLATON_CHECKORDERSTATUS \
  -DPLATON_GETINVOICE=$PLATON_GETINVOICE \
  -DPLATON_GETINVOICESLIST=$PLATON_GETINVOICESLIST \
  -DPLATON_GETPUBLICATIONS=$PLATON_GETPUBLICATIONS \
  -DPLATON_GETSTOCKS=$PLATON_GETSTOCKS \
  -DPLATON_ORDER=$PLATON_ORDER \
  -DPLATON_ORDER_DROP=$PLATON_ORDER_DROP \
  -DPLATON_PASSWORD=$PLATON_PASSWORD \
  -DPLATON_USER=$PLATON_USER \
  -DPROFILE=prod /app/b2bbase-0.1.jar"]