--liquibase formatted sql
--changeset dabrowskiw:1 dbms:mysql
CREATE TABLE product(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ean VARCHAR(15) UNIQUE NOT NULL,
    isbn VARCHAR(255),
    title VARCHAR(1000) NOT NULL,
    release_date VARCHAR(255),
    status VARCHAR(255),
    img LONGTEXT,
    author VARCHAR(255),
    series VARCHAR(255),
    translator VARCHAR(255),
    category_id BIGINT,
    publisher VARCHAR(255),
    description TEXT,
    release_year VARCHAR(10),
    cover_type VARCHAR(50),
    pages_number INT,
    width INT,
    height INT,
    edition INT,
    weight INT,
    vat VARCHAR(10),
    price DOUBLE,
    type VARCHAR(50),
    depth DOUBLE,
    approval_number VARCHAR(100),
    pcn VARCHAR(20),
    manufacturing_country_code VARCHAR(10),
    create_date TIMESTAMP,
    update_date TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

--liquibase formatted sql
--changeset dabrowskiw:1-h2 dbms:h2
CREATE TABLE product(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ean VARCHAR(15) UNIQUE NOT NULL,
    isbn VARCHAR(255),
    title VARCHAR(1000) NOT NULL,
    release_date VARCHAR(255),
    status VARCHAR(255),
    img LONGTEXT,
    author VARCHAR(255),
    series VARCHAR(255),
    translator VARCHAR(255),
    category_id BIGINT,
    publisher VARCHAR(255),
    description TEXT,
    release_year VARCHAR(10),
    cover_type VARCHAR(50),
    pages_number INT,
    width INT,
    height INT,
    edition INT,
    weight INT,
    vat VARCHAR(10),
    price DOUBLE,
    type VARCHAR(50),
    depth DOUBLE,
    approval_number VARCHAR(100),
    pcn VARCHAR(20),
    manufacturing_country_code VARCHAR(10),
    create_date TIMESTAMP,
    update_date TIMESTAMP
);
